name: TERRAFORM

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  # Job 1: Bootstrap
  bootstrap:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: ./terraform/bootstrap
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Check if storage account exists
        id: check_storage
        run: |
          if az storage account show --name tfstate --resource-group azurepilotdeploy >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

    

      - name: Terraform Init (no backend)
        if: steps.check_storage.outputs.exists == 'false'
        run: terraform init -backend=false

      - name: Terraform Apply bootstrap
        if: steps.check_storage.outputs.exists == 'false'
        run: terraform apply -auto-approve -target=azurerm_resource_group.main -target=azurerm_storage_account.tfstate -target=azurerm_storage_container.tfstate

  # Job 2: Main
  main:
    runs-on: ubuntu-latest
    needs: bootstrap   # espera a que termine bootstrap
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: ./terraform/main
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Clean local state 
        run: rm -rf .terraform terraform.tfstate*

      - name: Terraform Init (with backend)
        run: terraform init -migrate-state

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
